# This file is machine-generated by PrecompileSignatures.jl.
# Editing it directly is not advised.

precompile(Tuple{PrecompileSignatures.var"##precompilables#11", Bool, typeof(PrecompileSignatures.precompilables), Module})
precompile(Tuple{typeof(PrecompileSignatures._all_concrete), DataType})
precompile(Tuple{typeof(PrecompileSignatures._directives_datatypes), DataType, Bool})
precompile(Tuple{typeof(PrecompileSignatures._in_module), Module})
precompile(Tuple{typeof(PrecompileSignatures._module_functions), Module})
precompile(Tuple{typeof(PrecompileSignatures._split_union), DataType})
precompile(Tuple{typeof(PrecompileSignatures._unpack_union!), Union})
precompile(Tuple{typeof(PrecompileSignatures.precompilables), Module})
precompile(Tuple{typeof(PrecompileSignatures.precompile_directives)})